"""Evaluate dense, sparse and hybrid retrieval against a JSONL relevance set.

Expected JSONL format, one query per line:
{"query": "...", "relevant_chunk_ids": ["..."]}

The script deliberately keeps the relevance set external so it can be reviewed
and edited by a human rather than generated by the system being evaluated.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from rag_platform.embeddings import SentenceTransformerEmbeddingModel
from rag_platform.retrieval import BM25IndexStore, BM25Retriever, DenseRetriever, HybridRetriever, RRFFusion
from rag_platform.retrieval.evaluation import precision_at_k, recall_at_k, reciprocal_rank
from rag_platform.vector_store import ChromaVectorStore

MODEL_NAME = "BAAI/bge-small-en-v1.5"
VECTOR_STORE_ROOT = Path("data/processed/vector_store/ZCompanyLLC")
COLLECTION_NAME = "zcompany_hr_chunks"
DEFAULT_TOP_K = 5


def load_queries(path: Path) -> list[dict[str, object]]:
    records: list[dict[str, object]] = []
    with path.open(encoding="utf-8") as handle:
        for line in handle:
            if line.strip():
                record = json.loads(line)
                if not isinstance(record, dict):
                    raise ValueError("Each evaluation record must be an object.")
                records.append(record)
    return records


def main() -> None:
    parser = argparse.ArgumentParser(description="Evaluate dense, BM25 and hybrid retrieval.")
    parser.add_argument("relevance_file", type=Path)
    parser.add_argument("--top-k", type=int, default=DEFAULT_TOP_K)
    args = parser.parse_args()
    if args.top_k <= 0:
        raise ValueError("--top-k must be positive.")

    embedding_model = SentenceTransformerEmbeddingModel(MODEL_NAME)
    vector_store = ChromaVectorStore(
        path=VECTOR_STORE_ROOT,
        collection_name=COLLECTION_NAME,
        embedding_model=MODEL_NAME,
    )
    dense = DenseRetriever(embedding_model, vector_store)
    sparse = BM25Retriever(BM25IndexStore(VECTOR_STORE_ROOT / "bm25_index.json"))
    hybrid = HybridRetriever(dense, sparse, RRFFusion())

    rows: list[tuple[str, float, float, float, float, float, float]] = []
    totals = {"dense": [0.0, 0.0, 0.0], "sparse": [0.0, 0.0, 0.0], "hybrid": [0.0, 0.0, 0.0]}
    queries = load_queries(args.relevance_file)

    for record in queries:
        query = str(record["query"])
        relevant = [str(item) for item in record["relevant_chunk_ids"]]  # type: ignore[index]
        result_sets = {"dense": dense.retrieve(query, top_k=args.top_k),
                       "sparse": sparse.retrieve(query, top_k=args.top_k),
                       "hybrid": hybrid.retrieve(query, top_k=args.top_k)}
        metrics: dict[str, tuple[float, float, float]] = {}
        for name, results in result_sets.items():
            metrics[name] = (
                recall_at_k(results, relevant, args.top_k),
                precision_at_k(results, relevant, args.top_k),
                reciprocal_rank(results, relevant),
            )
            for i, value in enumerate(metrics[name]):
                totals[name][i] += value
        rows.append((query, *metrics["dense"], *metrics["sparse"], *metrics["hybrid"]))

    count = len(rows)
    if count == 0:
        print("No evaluation queries found.")
        return
    print(f"Queries: {count}; K={args.top_k}")
    print("system   Recall@K   Precision@K   MRR")
    for name in ("dense", "sparse", "hybrid"):
        values = [value / count for value in totals[name]]
        print(f"{name:<8} {values[0]:.4f}      {values[1]:.4f}        {values[2]:.4f}")


if __name__ == "__main__":
    main()
